# Generated by Django 4.2.23 on 2025-09-10 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0002_couponcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='coupon_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
