# Generated by Django 4.2.23 on 2025-09-19 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0003_alter_coupon_coupon_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='initial_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
