# Generated by Django 4.2.23 on 2025-08-08 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='status',
            field=models.CharField(default='out', max_length=16),
        ),
    ]
