# Generated by Django 4.2.23 on 2025-09-12 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0003_alter_table_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
