# Generated by Django 4.2.23 on 2025-09-21 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0004_table_deactivated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField()),
                ('usage_minutes', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booth.booth')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booth.table')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
