# Generated by Django 4.2.23 on 2025-09-23 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0005_tableusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='booth',
            name='event_dates',
            field=models.JSONField(blank=True, help_text="운영 날짜 목록 (예: ['2025-09-24', '2025-09-25'])", null=True),
        ),
        migrations.AddField(
            model_name='booth',
            name='host_name',
            field=models.CharField(blank=True, help_text='주최 이름 (없으면 빈 값 가능)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booth',
            name='location',
            field=models.CharField(blank=True, help_text='부스 위치', max_length=200, null=True),
        ),
    ]
