# Generated by Django 4.2.23 on 2025-09-23 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0006_booth_event_dates_booth_host_name_booth_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='booth',
            name='avg_table_usage_cache',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booth',
            name='day1_revenue_cache',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booth',
            name='day2_revenue_cache',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booth',
            name='day3_revenue_cache',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booth',
            name='turnover_rate_cache',
            field=models.FloatField(default=0.0),
        ),
    ]
