# Generated by Django 4.2.23 on 2025-09-23 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0007_booth_avg_table_usage_cache_booth_day1_revenue_cache_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booth',
            name='booth_image',
            field=models.ImageField(blank=True, help_text='부스 이미지 (Admin에서 업로드)', null=True, upload_to='booth_images/'),
        ),
    ]
