# Generated by Django 4.2.23 on 2025-09-18 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0003_alter_coupon_coupon_description'),
        ('cart', '0002_cart_created_at_cart_updated_at_alter_cartmenu_cart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='applied_coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_carts', to='coupon.coupon'),
        ),
    ]
