# Generated by Django 4.2.23 on 2025-08-02 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=100)),
                ('menu_category', models.CharField(max_length=100)),
                ('menu_price', models.FloatField()),
                ('menu_amount', models.IntegerField()),
                ('image', models.ImageField(upload_to='menu_images/')),
                ('discount_type', models.CharField(max_length=20)),
                ('discount_value', models.FloatField()),
                ('booth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booth.booth')),
            ],
        ),
        migrations.CreateModel(
            name='SetMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_name', models.CharField(max_length=100)),
                ('set_price', models.FloatField()),
                ('set_image', models.ImageField(upload_to='setmenu_images/')),
                ('discount_type', models.CharField(max_length=20)),
                ('discount_value', models.FloatField()),
                ('booth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booth.booth')),
            ],
        ),
        migrations.CreateModel(
            name='SetMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.menu')),
                ('set_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.setmenu')),
            ],
        ),
    ]
