# Generated by Django 4.2.23 on 2025-08-05 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='is_selling',
            field=models.BooleanField(default=True),
        ),
    ]
