# Generated by Django 4.2.23 on 2025-08-05 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menu_is_selling'),
    ]

    operations = [
        migrations.AddField(
            model_name='setmenu',
            name='set_category',
            field=models.CharField(default='세트', max_length=20),
        ),
        migrations.AddField(
            model_name='setmenu',
            name='set_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='setmenu',
            name='set_image',
            field=models.ImageField(blank=True, null=True, upload_to='setmenu_images/'),
        ),
        migrations.AlterField(
            model_name='setmenuitem',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='setmenuitem',
            name='set_menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='menu.setmenu'),
        ),
    ]
