# Generated by Django 4.2.23 on 2025-08-06 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_setmenu_set_category_setmenu_set_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='setmenu',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
