# Generated by Django 4.2.23 on 2025-08-10 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_menu_id_alter_setmenu_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='is_selling',
        ),
    ]
