# Generated by Django 4.2.23 on 2025-09-17 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_remove_menu_is_selling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu_category',
            field=models.CharField(choices=[('메뉴', '메뉴'), ('음료', '음료'), ('seat_fee', '테이블 이용료')], max_length=10),
        ),
    ]
