# Generated by Django 4.2.23 on 2025-08-04 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermenu',
            name='fixed_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordersetmenu',
            name='fixed_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('pending', '요청됨'), ('accepted', '접수됨'), ('cooked', '조리완료'), ('served', '서빙완료'), ('cancelled', '취소됨')], default='pending', max_length=20),
        ),
    ]
