# Generated by Django 4.2.23 on 2025-08-08 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_ordermenu_fixed_price_ordersetmenu_fixed_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTableFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_type', models.CharField(max_length=10)),
                ('quantity', models.IntegerField()),
                ('fixed_price', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
        ),
    ]
