# Generated by Django 4.2.23 on 2025-08-08 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_ordertablefee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderTableFee',
        ),
    ]
