# Generated by Django 4.2.23 on 2025-09-12 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_delete_ordertablefee'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='served_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
