# Generated by Django 4.2.23 on 2025-09-13 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_served_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermenu',
            name='ordersetmenu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_menus', to='order.ordersetmenu'),
        ),
    ]
