# Generated by Django 4.2.23 on 2025-09-13 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_ordermenu_ordersetmenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermenu',
            name='status',
            field=models.CharField(choices=[('pending', '대기'), ('cooked', '조리완료'), ('served', '서빙완료')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='ordersetmenu',
            name='status',
            field=models.CharField(choices=[('pending', '대기'), ('cooked', '조리완료'), ('served', '서빙완료')], default='pending', max_length=20),
        ),
    ]
