# Generated by Django 4.2.23 on 2025-09-16 03:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_ordermenu_status_ordersetmenu_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermenu',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordermenu',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ordersetmenu',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordersetmenu',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
