# Generated by Django 4.2.23 on 2025-09-17 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0004_table_deactivated_at'),
        ('order', '0008_ordermenu_created_at_ordermenu_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(default='직원 호출', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booth.booth')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booth.table')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
