# Generated by Django 4.2.23 on 2025-09-21 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_staffcall'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermenu',
            name='cooked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordermenu',
            name='served_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordersetmenu',
            name='cooked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordersetmenu',
            name='served_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
