# Generated by Django 4.2.23 on 2025-08-03 04:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('booth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='manager_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('table_num', models.IntegerField(default=1)),
                ('order_check_password', models.CharField()),
                ('account', models.CharField(max_length=100)),
                ('bank', models.CharField(max_length=100)),
                ('depositor', models.CharField(default='Unknown', max_length=20)),
                ('seat_type', models.CharField(choices=[('NO', 'No Seat Tax'), ('PP', 'Seat Tax Per Person'), ('PT', 'Seat Tax Per Table')], default='NO', max_length=2)),
                ('seat_tax_person', models.IntegerField()),
                ('seat_tax_table', models.IntegerField()),
                ('table_limit_hours', models.IntegerField()),
                ('table_qr_image', models.ImageField(blank=True, help_text='부스 전용 QR 코드 이미지', null=True, upload_to='qr_codes/')),
                ('booth', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='booth.booth')),
            ],
        ),
    ]
