# Generated by Django 4.2.23 on 2025-08-05 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_alter_manager_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='table_qr_image',
        ),
    ]
