# Generated by Django 4.2.23 on 2025-08-05 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_remove_manager_table_qr_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='order_check_password',
            field=models.CharField(max_length=100),
        ),
    ]
