# Generated by Django 4.2.23 on 2025-08-10 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_alter_manager_order_check_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='table_qr_image',
            field=models.ImageField(blank=True, help_text='부스 전용 QR 코드 이미지', null=True, upload_to='qr_codes/'),
        ),
    ]
