# Generated by Django 4.2.23 on 2025-09-17 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_manager_table_qr_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='seat_tax_person',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='seat_tax_table',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='seat_type',
            field=models.CharField(choices=[('NO', '없음'), ('PP', '1인당'), ('PT', '테이블당')], max_length=2),
        ),
    ]
